title: Frost Calculator by ZIP Code
description: Calculates the first and last freeze dates for a given ZIP code.


remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
